name = "pts-client-tools"
compatibility_date = "2026-06-30"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "pts_tax_lab"
database_id = "d78a145c-5f7a-4822-b7e1-8713343c9778"

[[r2_buckets]]
binding = "DOCS"
bucket_name = "pts-documents"

[[kv_namespaces]]
binding = "PTS_KV"
id = "e55023af345643c9aa6bb8173c86bdd6"
